sudo: required
services:
  - docker

before_install:
  - docker build -t gsoner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gsoner/react-test npm test -- --coverage


after_scucess:
  - docker build -t gsoner/mutli-client ./client
  - docker build -t gsoner/mutli-nginx ./nginx
  - docker build -t gsoner/mutli-server ./server
  - docker build -t gsoner/mutli-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gsoner/multi-client
  - docker push gsoner/multi-nginx
  - docker push gsoner/multi-server
  - docker push gsoner/multi-worker
