sudo: required
services:
  - docker

before_install:
  - docker build -t gsoner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gsoner/react-test npm test -- --coverage

after_success:
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t docker.io/gsoner/mutli-client:latest ./client
  - docker build -t docker.io/gsoner/mutli-nginx:latest ./nginx
  - docker build -t docker.io/gsoner/mutli-server:latest ./server
  - docker build -t docker.io/gsoner/mutli-worker:latest ./worker

  # Take those images and push them to docker hub
  - docker push docker.io/gsoner/multi-client:latest
  - docker push docker.io/gsoner/multi-nginx:latest
  - docker push docker.io/gsoner/multi-server:latest
  - docker push docker.io/gsoner/multi-worker:latest
