sudo: required
services:
  - docker

before_install:
  - docker build -t gsoner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gsoner/react-test npm test -- --coverage

after_success:
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t gsoner/multi-client:latest ./client
  - docker build -t gsoner/multi-nginx:latest ./nginx
  - docker build -t gsoner/multi-server:latest ./server
  - docker build -t gsoner/multi-worker:latest ./worker
  - docker images
  # Take those images and push them to docker hub
  - docker push gsoner/multi-client
  - docker push gsoner/multi-nginx
  - docker push gsoner/multi-server
  - docker push gsoner/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-270015325157
  bucket_patch: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY